language: php
php:
  - 5.5
services:
    - redis-server
install: 
    - ./scripts/build/install_zf.sh
    - printf "\n" | pecl install imagick
before_script:
    - phpenv config-add scripts/build/phpconf.ini
script: phpunit -c tests/phpunit.xml
