<a id="forkme" href="https://github.com/Umkus/unsee.cc/"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://github-camo.global.ssl.fastly.net/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png"></a>

<div id="header">
    <img src="/img/logo.png" id="logo" alt="Walther" width="200" height="144" />
    <p><?=$this->translate('slogan')?></p>
</div>

<div id="body">
    <div id="info">
        <p class="info">
            <span id="life_time_container">
                <b>
                    <?=$this->translate('delete')?>
                    <span id="life_time_selectors_container">
                    <select id="life_time">
                        <option value="fist"><?=$this->translate('after_view')?></option>
                        <option value="hour"><?=$this->translate('after_hour')?></option>
                        <option value="day"><?=$this->translate('after_day')?></option>
                        <option value="week"><?=$this->translate('after_week')?></option>
                    </select>
                    <a id="fake_select" href="" onclick="return false;"><?=$this->translate('after_view')?></a>
                </span>
                </b>
            </span>
        </p>
    </div>
    <div class="arrow_container">
        <div class="arrow"></div>
    </div>

    <div class="button">
        <input type="file" id="fakeFileupload" name="image[]" multiple />
        <p><?=$this->translate('choose_images')?></p>
        <span><?=$this->translate('drag')?></span>
    </div>

    <div id="loading">
        <img src="/img/loading.gif" alt="loading..."/>
    </div>
    <div id="success">
        <div id="about">
            <?=$this->translate('intro')?>
        </div>

        <strong><?=$this->translate('uploaded')?></strong>
        <input id="imgLink" type="text" value="" />
        <button id="view" class="copy"><?=$this->translate('open')?></button>
    </div>
    <div id="error">
        <strong></strong>
    </div>
</div>