<div id="header">
    <img src="<?=$this->assetsDomain;?>/img/logo.png" id="logo" alt="Walther" width="200" height="144" />
    <p><?=$this->translate('slogan')?></p>
</div>

<div id="langs">
    <p></p>
</div>

<div id="body">
    <div id="info">
        <p class="info">
            <span><?=$this->translate('click')?></span>
            <span id="life_time_container">
                <b>
                    <?=$this->translate('delete')?>
                    <span id="life_time_selectors_container">
                    <select id="life_time">
                        <option value="fist"><?=$this->translate('after_view')?></option>
                        <option value="hour"><?=$this->translate('after_hour')?></option>
                        <option value="day"><?=$this->translate('after_day')?></option>
                        <option value="week"><?=$this->translate('after_week')?></option>
                    </select>
                    <a id="fake_select" href="" onclick="return false;"><?=$this->translate('after_view')?></a>
                </span>
                </b>
            </span>
        </p>
    </div>
    <div class="arrow_container">
        <div class="arrow"></div>
    </div>

    <div class="button">
        <input type="file" id="fakeFileupload" name="image[]" multiple />
        <p><?=$this->translate('choose_images')?></p>
        <span><?=$this->translate('drag')?></span>
    </div>

    <div id="loading">
        <img src="<?=$this->assetsDomain;?>/img/loading.gif" alt="loading..."/>
    </div>
    <div id="success">
        <div id="about">
            <?=$this->translate('intro')?>
        </div>

        <strong><?=$this->translate('uploaded')?></strong>
        <input id="imgLink" type="text" value="" />
        <button id="view" class="copy"><?=$this->translate('open')?></button>
    </div>
    <div id="error">
        <strong></strong>
    </div>
</div>