<?php
$this->headMeta()->appendName('robots', 'noindex');
?>

<div id="header">
    <a href="/"><img src="<?= $this->assetsDomain; ?>/img/logo.png" id="logo" alt="Unsee" width="200" height="144" /></a>
    <p><?= $this->translate('slogan') ?></p>
    <div id="settings">
        <form method="post" action="">
            <ul>
                <?php
                $groups = array_values($this->groups);

                foreach ($groups as $key => $group) {
                ?>
                <li data-page="<?=$group->getName()?>" class="<? if (!$key) { ?> active<? } ?>"><?=$group->getLegend()?><div /></li>
                <?php
                }
                ?>
            </ul>

            <?php
            foreach ($groups as $gKey=>$group) {
            ?>
            <table class="<?=$group->getName()?>">
            <?
                $fields = array_values($group->getElements());

                foreach ($fields as $key=>$field) {
            ?> 
                <tr>
                    <td class="key"><?=$field->renderLabel()?></td><? if(!$key){ ?><td class="separator" rowspan="<?=count($fields);?>"><div/></td><?}?> 
                    <td class="value"><?=$field->render()?></td> 
                </tr> 
            <?
                }
            ?> 
            </table>
            <?
            }
            ?> 
            <input type="submit" />
        </form>
    </div>
</div>

<div id="imgMessage"> <b><?= $this->deleteTime ?></b> <span>(<?= $this->translate('click_settings'); ?>)</span> </div>
<?
if ($this->title) {
?>
<div class="title"><h3><?=$this->title;?></h3></div>
<?
}

if ($this->description) {
?>
<div class="description"><p><?=$this->description;?></p></div>
<?
}
?>

<?php
if ($this->no_download) {

    ?>
    <div id="screen"></div>
    <?php
}
?>

<?php
foreach ($this->images as $imgDoc) {

    ?>
    <img style="max-width: <?=$imgDoc->width;?>px;" src="/image/<?= (string)$imgDoc->_id; ?>/<?= $imgDoc->md5; ?>/<?= $imgDoc->ticketTtd; ?>" alt="" />
    <?php
}