<?php
$this->headMeta()->appendName('robots', 'noindex');
?>

<div id="header">
    <a href="/"><img src="<?= $this->assetsDomain; ?>/img/logo.png" id="logo" alt="Unsee" width="200" height="144" /></a>
    <p><?= $this->translate('slogan') ?></p>
    <div id="settings">
        <ul>
            <?php
            $groups = array_values($this->groups);

            foreach ($groups as $key => $group) {
            ?>
            <li data-page="<?=$group->getName()?>" class="<? if (!$key) { ?> active<? } ?>"><?=$group->getLegend()?><div /></li>
            <?php
            }
            ?>
        </ul>

        <?php
        foreach ($groups as $gKey=>$group) {
        ?>
        <table class="<?=$group->getName()?>">
        <?
            $fields = array_values($group->getElements());

            foreach ($fields as $key=>$field) {
        ?> 
            <tr>
                <td class="key"><?=$field->renderLabel()?></td><? if(!$key){ ?><td class="separator" rowspan="<?=count($fields);?>"><div/></td><?}?> 
                <td class="value"><?=$field->renderViewHelper()?></td> 
            </tr> 
        <?
            }
        ?> 
        </table>
        <?
        }
        ?> 

        <button disabled="disabled">Apply</button>

    </div>
</div>

<?php
if (!$this->isOwner) {

    ?>
    <div id="screen"></div>
    <?php
}

?>
<div id="imgMessage"> <b><?= $this->deleteTime ?></b> <span>(<?= $this->translate('click_settings'); ?>)</span> </div>
<?php
foreach ($this->images as $imageId => $imageData) {

    ?>
    <img src="/image/<?= $imageId; ?>/<?= $imageData['hash']; ?>/<?= $imageData['ticketTtd']; ?>" alt="" />
    <?php
}