<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]-->
    <head>
        <meta name="google-site-verification" content="9e0q8l5-WWl83HrKaZ0nGM5jMHnKpis_7O79L4tYUV0" />
        <meta name='yandex-verification' content='74b69306dc3139b8' />
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title><?=$this->translate('slogan')?></title>
        <meta name="description" content="<?=$this->translate('slogan')?>" />
        <meta name="keywords" content="<?=$this->translate('keywords')?>" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=2.0, user-scalable=1, target-densitydpi=device-dpi" />
        <?=$this->headMeta()?>

        <!-- Link css resources -->
        <?=$this->cssHelper()?>

        <!-- Link js scripts -->
        <?=$this->javascriptHelper()?>

    </head>
    <body>
        <!--[if lt IE 8]>
        <p class="chromeframe">outdated</p>
        <![endif]-->

        <?=$this->layout()->content?>

        <div id="footer">
            <!--
            <ul>
                <li><a href="/about/"><?=$this->translate('about')?></a></li>
                <li><a href="/terms/"><?=$this->translate('terms')?></a></li>
                <li><a href="/privacy/"><?=$this->translate('privacy')?></a></li>
                <li><a href="/contact/"><?=$this->translate('contact')?></a></li>
            </ul>
            -->
        </div>
    </body>
</html>