<div id="header">
    <a href="/">
        <img src="/img/logo.png" id="logo" alt="Walther" width="200" height="144" />
    </a>
</div>

<h1><?= $this->translate('contact'); ?></h1>
<div id="text">
    <table align="center" id="contactForm">
        <tr>
            <td width="33%"><?= $this->form->type->renderLabel(); ?></td>
            <td align="right"> 
                <?= $this->form->type->render(); ?> 
            </td>
        </tr>
        <tr>
            <td><?= $this->form->name->renderLabel(); ?></td>
            <td><?= $this->form->name->render(); ?></td>
        </tr>
        <tr>
            <td><?= $this->form->email->renderLabel(); ?></td>
            <td><?= $this->form->email->render(); ?></td>
        </tr>
        <tr>
            <td colspan="2">
                <?= $this->form->message->render(); ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <span id="success"><strong><?= $this->translate('message_sent') ?></strong></span>
                <span id="error"><strong><?= $this->translate('message_errors') ?></strong></span>
                <?= $this->form->send->render(); ?>
            </td>
        </tr>
    </table>
</div>